### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by ymichel**
Adding Geolocation plugin to the list of supported plugins

### CODE REVIEW

**Comment by scrobbleme** [comment]
@ymichel Thank you, I had no time yet to look into it.

Lately I added some automagic settings for Leaflet.
-> if your plugins has some filters to change the (default) URLs, this would be nice as well.

**Comment by ymichel** [comment]
Could you please add the link to the supported plugins. Thx.

**Comment by scrobbleme** [comment]
@ymichel Thank you and sorry for the delay. I wanted to test this first.

Nice solution.

If you want, you could change your plugin to use the proxy automatically, when my plugin is installed. I would prefer if other plugins handle this on their own.

See: https://github.com/moewe-io/osm-tiles-proxy/blob/master/includes/plugin.leaflet-map.php

What is happening there:

* OSM Tiles Proxy hook into WordPress "options" for the Leaflet JS plugin
* and overwrites the default settings for the URLs
  * only if no custom settings are used
* ->  if OSM Tiles Proxy is deactivated again, everything is back to normal

The code may look like this (not tested):

```
add_filter('default_option_geolocation_osm_tiles_url', function ($default) {
    return apply_filters('osm_tiles_proxy_get_proxy_url', $default);
}, 10, 1);
```

**Comment by ymichel** [comment]
I have added it similarly:
In case the Proxy is installed, geolocation will offer to use it with a checkbox. In case it is not checked or the proxy is not installed, my plugin will use its own capabilities or the OSM tiles as usual. 
Thanks for your support.

**Pull request merged**
